#!/bin/bash

#===============================================================================
# SCRIPT: 14_ses_overlap_plots.sh
# PURPOSE: Generate plots and summary statistics from the SES overlap analysis.
#
# DESCRIPTION:
# This script serves as a wrapper to execute an R script that visualizes the
# results from '13_ses_overlap.sh'. It finds the statistical output files
# from the previous step and passes them to an R script, which then generates
# publication-quality plots (e.g., bar charts) comparing the overlap
# percentages across different samples and conditions.
#
# KEY OPERATIONS:
# 1. Activates a conda environment containing R and required plotting libraries.
# 2. Validates that the output directory from the overlap analysis exists.
# 3. Counts the number of statistics files to ensure there is data to process.
# 4. Executes the 'ses_overlap_plots.R' script to perform the visualization.
# 5. Reports on the success or failure of the R script execution.
# 6. Lists the generated plot files and prints summary tables to the log.
#
# METHODOLOGY:
# The script automates the plotting process by orchestrating the execution of a
# dedicated R script ('scripts/ses_overlap_plots.R'). All complex data parsing,
# statistical summarization, and plotting logic is encapsulated within the R
# script, promoting separation of concerns. This shell script's role is to
# manage the environment, inputs, and execution flow.
#
# IMPORTANT PARAMETERS:
# - The primary configuration is the path to the R script itself:
#   'scripts/ses_overlap_plots.R'.
# - SLURM parameters (--mem, --time, etc.) define computational resources.
#
# INPUTS:
# - Statistics files generated by '13_ses_overlap.sh', located in
#   `results/13_ses_overlap/`, specifically files matching `*_ses_stats.txt`.
#
# OUTPUTS:
# - PNG plot files saved in `results/13_ses_overlap/plots/`.
# - A CSV file with summary statistics:
#   `results/13_ses_overlap/plots/summary_statistics.csv`.
# - A text file with a high-level analysis summary:
#   `results/13_ses_overlap/plots/analysis_summary.txt`.
#
# DEPENDENCIES:
# - R programming language.
# - R libraries (e.g., ggplot2, dplyr) specified within the R script.
# - A conda environment named 'peak_calling' where R and its packages are installed.
# - The R script 'scripts/ses_overlap_plots.R'.
#===============================================================================

#SBATCH --job-name=14_ses_plots
#SBATCH --account=kubacki.michal
#SBATCH --mem=8GB
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kubacki.michal@hsr.it
#SBATCH --error="./logs/14_ses_overlap_plots.err"
#SBATCH --output="./logs/14_ses_overlap_plots.out"

# Initialize conda for the current shell
echo "Initializing conda..."
eval "$(conda shell.bash hook)"

# Activate R environment
echo "Activating R environment..."
conda activate peak_calling

BASE_DIR="/beegfs/scratch/ric.sessa/kubacki.michal/SRF_Eva_top/SRF_Eva_CUTandTAG"
cd $BASE_DIR

echo "Starting SES overlap graphical analysis..."
echo "Input directory: results/13_ses_overlap/"
echo "Output directory: results/13_ses_overlap/plots/"

# Check if overlap analysis results exist
if [ ! -d "results/13_ses_overlap" ]; then
    echo "ERROR: Overlap analysis results not found!"
    echo "Please run 13_ses_overlap.sh first to generate overlap statistics."
    exit 1
fi

# Count stats files
stats_count=$(find results/13_ses_overlap -name "*_ses_stats.txt" | wc -l)
echo "Found ${stats_count} statistics files to process"

if [ ${stats_count} -eq 0 ]; then
    echo "ERROR: No statistics files found in results/13_ses_overlap/"
    echo "Please ensure 13_ses_overlap.sh completed successfully."
    exit 1
fi

# Run R script for graphical analysis
echo "Running R script for SES overlap visualization..."
Rscript scripts/ses_overlap_plots.R

# Check if R script completed successfully
if [ $? -eq 0 ]; then
    echo ""
    echo "SES overlap graphical analysis completed successfully!"
    echo ""
    echo "Generated plots and files:"
    ls -la results/13_ses_overlap/plots/
    echo ""
    echo "Summary statistics:"
    if [ -f "results/13_ses_overlap/plots/summary_statistics.csv" ]; then
        echo ""
        cat results/13_ses_overlap/plots/summary_statistics.csv
    fi
    echo ""
    echo "View the analysis summary:"
    if [ -f "results/13_ses_overlap/plots/analysis_summary.txt" ]; then
        echo ""
        cat results/13_ses_overlap/plots/analysis_summary.txt
    fi
else
    echo "ERROR: R script failed with exit code $?"
    echo "Check the R script output above for details."
    exit 1
fi

echo ""
echo "SES overlap graphical analysis complete!"
echo "Results saved in: results/13_ses_overlap/plots/"